[package]
name = "smelter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.8"
indicatif = "0.17.7"
walkdir = "2.4.0"
glob = "0.3.0"